/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppUnitsRouteImport } from './routes/app.units'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSmsLogsRouteImport } from './routes/admin.sms-logs'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicCronExpiryCheckRouteImport } from './routes/api/public/cron/expiry-check'
import { Route as ApiPublicBkashCallbackRouteImport } from './routes/api/public/bkash/callback'

const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsLogsRoute = AdminSmsLogsRouteImport.update({
  id: '/sms-logs',
  path: '/sms-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronExpiryCheckRoute =
  ApiPublicCronExpiryCheckRouteImport.update({
    id: '/api/public/cron/expiry-check',
    path: '/api/public/cron/expiry-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBkashCallbackRoute = ApiPublicBkashCallbackRouteImport.update({
  id: '/api/public/bkash/callback',
  path: '/api/public/bkash/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/sms-logs': typeof AdminSmsLogsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/products': typeof AppProductsRoute
  '/app/stock': typeof AppStockRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/units': typeof AppUnitsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/bkash/callback': typeof ApiPublicBkashCallbackRoute
  '/api/public/cron/expiry-check': typeof ApiPublicCronExpiryCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/sms-logs': typeof AdminSmsLogsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/products': typeof AppProductsRoute
  '/app/stock': typeof AppStockRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/units': typeof AppUnitsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/bkash/callback': typeof ApiPublicBkashCallbackRoute
  '/api/public/cron/expiry-check': typeof ApiPublicCronExpiryCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/sms-logs': typeof AdminSmsLogsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/products': typeof AppProductsRoute
  '/app/stock': typeof AppStockRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/units': typeof AppUnitsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/bkash/callback': typeof ApiPublicBkashCallbackRoute
  '/api/public/cron/expiry-check': typeof ApiPublicCronExpiryCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/renew'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/shops'
    | '/admin/sms-logs'
    | '/admin/subscriptions'
    | '/app/categories'
    | '/app/products'
    | '/app/stock'
    | '/app/subscription'
    | '/app/units'
    | '/admin/'
    | '/app/'
    | '/api/public/bkash/callback'
    | '/api/public/cron/expiry-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/renew'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/shops'
    | '/admin/sms-logs'
    | '/admin/subscriptions'
    | '/app/categories'
    | '/app/products'
    | '/app/stock'
    | '/app/subscription'
    | '/app/units'
    | '/admin'
    | '/app'
    | '/api/public/bkash/callback'
    | '/api/public/cron/expiry-check'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/renew'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/shops'
    | '/admin/sms-logs'
    | '/admin/subscriptions'
    | '/app/categories'
    | '/app/products'
    | '/app/stock'
    | '/app/subscription'
    | '/app/units'
    | '/admin/'
    | '/app/'
    | '/api/public/bkash/callback'
    | '/api/public/cron/expiry-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RenewRoute: typeof RenewRoute
  ApiPublicBkashCallbackRoute: typeof ApiPublicBkashCallbackRoute
  ApiPublicCronExpiryCheckRoute: typeof ApiPublicCronExpiryCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/units': {
      id: '/app/units'
      path: '/units'
      fullPath: '/app/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms-logs': {
      id: '/admin/sms-logs'
      path: '/sms-logs'
      fullPath: '/admin/sms-logs'
      preLoaderRoute: typeof AdminSmsLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron/expiry-check': {
      id: '/api/public/cron/expiry-check'
      path: '/api/public/cron/expiry-check'
      fullPath: '/api/public/cron/expiry-check'
      preLoaderRoute: typeof ApiPublicCronExpiryCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bkash/callback': {
      id: '/api/public/bkash/callback'
      path: '/api/public/bkash/callback'
      fullPath: '/api/public/bkash/callback'
      preLoaderRoute: typeof ApiPublicBkashCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminSmsLogsRoute: typeof AdminSmsLogsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminSmsLogsRoute: AdminSmsLogsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppStockRoute: typeof AppStockRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppProductsRoute: AppProductsRoute,
  AppStockRoute: AppStockRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RenewRoute: RenewRoute,
  ApiPublicBkashCallbackRoute: ApiPublicBkashCallbackRoute,
  ApiPublicCronExpiryCheckRoute: ApiPublicCronExpiryCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
